USE teste_3;
CREATE TABLE relatorio_cadop_teste3 (
	RegistroANS INT(15) NOT NULL PRIMARY KEY,
    CNPJ VARCHAR(20),
    RazaoSocial VARCHAR(160),
    NomeFantasia VARCHAR(90),
    Modalidade VARCHAR(40),
    Logradouro VARCHAR(60),
    Numero VARCHAR(25),
    Complemento VARCHAR(60),
    Bairro VARCHAR(40),
    Cidade VARCHAR(35),
    UF VARCHAR(2),
    CEP INT(8),
    DDD VARCHAR(2),
    Telefone VARCHAR(12),
    Fax VARCHAR(12),
    EnderecoEletronico VARCHAR(80),
    Representante VARCHAR(100),
    CargoRepresentante VARCHAR(100),
    DataRegistroANS VARCHAR(11)
) ENGINE=InnoDB;

CREATE TABLE demonstracoes (
	DATA VARCHAR(12),
    REG_ANS INT(15),
    CD_CONTA_CONTABIL VARCHAR(15),
    DESCRICAO TEXT,
    VL_SALDO_FINAL VARCHAR(15)
) ENGINE=InnoDB;

ALTER TABLE demonstracoes ADD CONSTRAINT fk_RegistroANS FOREIGN KEY(REG_ANS) REFERENCES relatorio_cadop_teste3 (RegistroANS);

SET FOREIGN_KEY_CHECKS=0;

LOAD DATA INFILE 'Relatorio_cadop teste 3.csv' INTO TABLE relatorio_cadop_teste3 FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 3 ROWS;

LOAD DATA INFILE '1T2020.csv' INTO TABLE demonstracoes FIELDS ENCLOSED BY '"' TERMINATED BY ';' LINES TERMINATED BY '\r\n'  IGNORE 1 ROWS;
LOAD DATA INFILE '2T2020.csv' INTO TABLE demonstracoes FIELDS ENCLOSED BY '"' TERMINATED BY ';' LINES TERMINATED BY '\r\n'  IGNORE 1 ROWS;
LOAD DATA INFILE '3T2020.csv' INTO TABLE demonstracoes FIELDS ENCLOSED BY '"' TERMINATED BY ';' LINES TERMINATED BY '\r\n'  IGNORE 1 ROWS;
LOAD DATA INFILE '4T2020.csv' INTO TABLE demonstracoes FIELDS ENCLOSED BY '"' TERMINATED BY ';' LINES TERMINATED BY '\r\n'  IGNORE 1 ROWS;

LOAD DATA INFILE '1T2021.csv' INTO TABLE demonstracoes FIELDS ENCLOSED BY '"' TERMINATED BY ';' LINES TERMINATED BY '\r\n'  IGNORE 1 ROWS;
LOAD DATA INFILE '2T2021.csv' INTO TABLE demonstracoes FIELDS ENCLOSED BY '"' TERMINATED BY ';' LINES TERMINATED BY '\r\n'  IGNORE 1 ROWS;
LOAD DATA INFILE '3T2021.csv' INTO TABLE demonstracoes FIELDS ENCLOSED BY '"' TERMINATED BY ';' LINES TERMINATED BY '\r\n'  IGNORE 1 ROWS;

ALTER TABLE demonstracoes
ADD COLUMN VL_SALDO_INCIAL VARCHAR(15) AFTER DESCRICAO;
LOAD DATA INFILE '4T2021.csv' INTO TABLE demonstracoes FIELDS ENCLOSED BY '"' TERMINATED BY ';' LINES TERMINATED BY '\r\n'  IGNORE 1 ROWS;

SET FOREIGN_KEY_CHECKS=1;
